---
sudo_configs:
  - name: 000_root
    content: |
      root ALL=(ALL) NOPASSWD: ALL
  - name: 100_wheel
    content: |
      Defaults:%wheel !requiretty
      %wheel ALL=(ALL) ALL
  - name: 200_vagrant
    content: |
      Defaults:vagrant !requiretty
      vagrant ALL=(ALL) NOPASSWD: ALL
  - name: vagrant
    state: absent

project_pf_ssh_from: []

project_virtual_user_credentials:
  - "john@trombik.org:$2b$08$LT/AdE2YSHb19d3hB27.4uXd1/Cj0qQIWc4FdfLlcuqnCUGbRu2Mq::::::"
project_virtuals:
  - abuse@trombik.org john@trombik.org
  - postmaster@trombik.org john@trombik.org
  - john@trombik.org {{ opensmtpd_virtual_user.name }}
project_users:
  - comment: Tomoyuki Sakurai
    group: wheel
    groups:
    - wheel
    name: trombik
    # PassWord
    password:
      OpenBSD: "$2b$08$0AezJpO1H/1al0GG7aFuou90P0ueUFkjQ.hKeP2.T0dz09vrVQH32"
    ssh_public_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCaf3bNJ3CUGVdDTM/5e6PgFEnRAEnNCyESKof9Hu+bnPWWYmmLy0bYgZTGOmbVmn5O4RAiGEKkcBjXt6X95az/IteZZDrIFP6qqaJIAEMmLaAs2u6vnQWczb9Gm8xnMQF6ttjY1TL532PAFh3c9q55vFmurBJDad6KAWcpnVQrlo9OIJYTnn2rkWSgfmuw1OBGbB6iREfWnLOYbyPDVXxQPX+x0qMah4xPmq/P7bp0lc3wGT2OORvEaU7C1WwPm0EUUucpEGdGXLbkTlL08ymiSNSztCWdeGO5trNbCCEoVoN06oPHmNE/LB0gJX6XFJeg8epeZUIic+TAlkrpmTZX foo@bar
    ssh_rc: |
      # XXX sshd(8) states that the script "must not produce any output on
      # stdout"
      set -e
      if [ ! -d dotfiles ]; then
        git clone https://github.com/trombik/dotfiles.git >/dev/null
        (cd dotfiles && sh install.sh >/dev/null)
      fi
