---
project_virtual_user_credentials:
    - john@trombik.org $2b$08$LT/AdE2YSHb19d3hB27.4uXd1/Cj0qQIWc4FdfLlcuqnCUGbRu2Mq
project_virtuals:
  - abuse@trombik.org john@trombik.org
  - postmaster@trombik.org john@trombik.org
  - john@trombik.org {{ opensmtpd_virtual_user.name }}
