# Generated by `infrataster init`

require "English"
require "rake"
require "rspec/core/rake_task"
require "yaml"
require "net/ssh"
require "tempfile"
require "pathname"
require "highline/import"
require "ansible/inventory/yaml"
require "vagrant/serverspec"
require "vagrant/ssh/config"

def exec_and_abort_if_fail(cmd)
  status = system cmd
  warn "`#{cmd}` failed." unless $CHILD_STATUS.exitstatus.zero?
  abort unless $CHILD_STATUS.exitstatus.zero?
  status
end

def vagrant(args)
  Bundler.with_clean_env do
    exec_and_abort_if_fail "vagrant #{args}"
  end
end

def ansible_environment
  ENV["ANSIBLE_ENVIRONMENT"] ? ENV["ANSIBLE_ENVIRONMENT"] : "virtualbox"
end

def inventory_file
  "inventories/#{ansible_environment}/#{ansible_environment}.yml"
end

def sudo_password
  ask("Enter sudo password: ") { |q| q.echo = false }
end

def sudo_password_required?(user)
  user != "root" && user != "vagrant"
end

def configure_sudo_password_for(run_as_user)
  ENV["SUDO_PASSWORD"] = sudo_password if
    sudo_password_required?(run_as_user) &&
    !ENV.key?("SUDO_PASSWORD")
end

desc "vagrant up"
task :up do
  vagrant "up"
end

desc "destroy VMs by `vagrant destroy`"
task :clean do
  vagrant "destroy -f"
end

desc "vagrant provision"
task :provision do
  vagrant "provision"
end

desc "all all tests; serverspec, integration, and rubocop"
task test: [
  # probably, each target deserves its own Jenkins stage. but for now, I would
  # like to merge the branch first. or, the branch history will mess up.
  "test:rubocop:all",
  :up,
  "test:serverspec:all",
  "test:integration:all"
] do
end

# rubocop:disable Metrics/BlockLength:
namespace :test do
  desc "Prepare"
  task :prepare do
    vagrant "up"
    vagrant "provision"
  end

  desc "Provision"
  task :provision do
    vagrant "provision"
  end

  desc "Restart VMs"
  task :restart do
    vagrant "reload --provision"
  end

  desc "Clean"
  task :clean do
    begin
      vagrant "destroy -f"
    ensure
      sh "rm -f *.vdi"
    end
  end

  namespace "serverspec" do
    inventory = Ansible::Inventory::YAML.new(inventory_file)
    desc "Run serverspec on all hosts"
    task "all" do
      inventory.all_groups.each do |g|
        next unless Dir.exist?("spec/serverspec/#{g}")
        inventory.all_hosts_in(g).each do |h|
          # XXX pass SUDO_PASSWORD to serverspec if the user is required to
          # type password
          run_as_user = Vagrant::SSH::Config.for(h)["User".downcase]
          configure_sudo_password_for(run_as_user)
          puts "running serverspec for #{g} on #{h} as user `#{run_as_user}`"
          Vagrant::Serverspec.new(inventory_file).run(group: g, hostname: h)
        end
      end
    end
    inventory.all_groups.each do |g|
      next unless Dir.exist?("spec/serverspec/#{g}")
      desc "Run serverspec for group `#{g}`"
      task g.to_sym do |_t|
        inventory.all_hosts_in(g).each do |h|
          # XXX !DRY
          run_as_user = Vagrant::SSH::Config.for(h)["User".downcase]
          configure_sudo_password_for(run_as_user)
          puts "running serverspec for #{g} on #{h} as user `#{run_as_user}`"
          Vagrant::Serverspec.new(inventory_file).run(group: g, hostname: h)
        end
      end
    end
  end

  # XXX replace `serverspec` namespace with this when it is confirmed that the
  # tasks are acutually faster.
  namespace "para" do
    inventory = Ansible::Inventory::YAML.new(inventory_file)
    inventory.all_groups.each do |g|
      next unless Dir.exist?("spec/serverspec/#{g}")
      inventory.all_hosts_in(g).each do |h|
        # XXX hide the tasks from the task list because it can be tested only
        # with remote hosts, not VMs on the same machine.
        #
        # desc "Run serverspec for group `#{g}` on #{h}"
        task "#{g}:#{h}" do |_t|
          Vagrant::Serverspec.new(inventory_file)
                             .run_with_fork(group: g, hostname: h)
        end
      end
    end

    inventory.all_groups.each do |g|
      next unless Dir.exist?("spec/serverspec/#{g}")
      # XXX hide the tasks from the task list because it can be tested only
      # with remote hosts, not VMs on the same machine.
      #
      # desc "Run serverspec for group `#{g}`"
      hosts = inventory.all_hosts_in(g)
      task g.to_sym => hosts.map { |h| "test:para:#{g}:#{h}" } do |_t|
        Process.waitall
      end
    end
  end

  namespace "integration" do
    # set the default user name in each environment
    run_as_user = case ansible_environment
                  when "virtualbox"
                    "vagrant"
                  when "prod"
                    ENV["USER"]
                  end

    # but if ANSIBLE_USER is defined by the user, override it
    run_as_user = ENV["ANSIBLE_USER"] if ENV["ANSIBLE_USER"]
    directories = Pathname.glob("spec/integration/[0-9][0-9][0-9]_*")
    directories.each do |d|
      desc "run integration spec #{d.basename}"
      task d.basename.to_s do
        vault_password_file = ENV["ANSIBLE_VAULT_PASSWORD_FILE"]
        test_env = ansible_environment
        Bundler.with_clean_env do
          ENV["ANSIBLE_ENVIRONMENT"] = test_env
          ENV["ANSIBLE_VAULT_PASSWORD_FILE"] = vault_password_file
          configure_sudo_password_for(run_as_user)
          sh "bundle exec rspec #{d}/*_spec.rb"
        end
      end
    end
    desc "Run integration test"
    task :all do
      # XXX run `bundler exec rspec` in a clean environment.
      # the difference from running `rspec` in bundler environment is that:
      # when invoking `rspec` within `with_clean_env`, the forked process can
      # escape, or shellout, from the bundler environment.
      #
      # `rspec` is a different process. when you invoke `rspec` without
      # `with_clean_env`, the bundler in `rspec` process keeps a copy of
      # original environemnt and replace current environment with the copy when
      # inside of `with_clean_env`. but because, in this case, the copied
      # environment inherits the bundler environment of `rake`, the environment
      # the process replaced is still bundler environment.
      vault_password_file = ENV["ANSIBLE_VAULT_PASSWORD_FILE"]
      test_env = ansible_environment
      Bundler.with_clean_env do
        ENV["ANSIBLE_ENVIRONMENT"] = test_env
        ENV["ANSIBLE_VAULT_PASSWORD_FILE"] = vault_password_file
        configure_sudo_password_for(run_as_user)
        sh "bundle exec rspec spec/integration/**/*_spec.rb"
      end
    end
  end

  namespace "rubocop" do
    desc "Run rubocop"
    task :all do
      sh "rubocop --display-cop-names --display-style-guide"
    end
  end
end
# rubocop:enable Metrics/BlockLength:
