---
- name: trombik.vim
- name: trombik.zsh
- name: trombik.hostname
- name: trombik.hosts
- name: trombik.opensmtpd
- name: trombik.x509_certificate
- name: trombik.dovecot
- name: trombik.git
- name: trombik.pf
- name: trombik.sudo
