---
_meta:
  terraform:
    mx1.trombik.org:
      ami: ami-04af7ec1b9ea369dd
      tags:
        Name: mx1.trombik.org
        stage: staging

all:
  hosts:
  children:
    mx1.trombik.org:
      hosts:
        mx1_trombik_org:
      vars:
        ansible_python_interpreter: /usr/local/bin/python3
    mx:
      children:
        mx1.trombik.org:

    staging-mx:
      children:
        mx:

    staging-credentials:
      children:
        mx:

    staging:
      children:
        staging-mx:
