---
- hosts:
  - mx
  become: yes
  become_method: "{% if 'virtualbox' in group_names %}sudo{% else %}doas{% endif %}"
  environment:
    http_proxy: "{{ http_proxy | default() }}"
    https_proxy: "{{ https_proxy | default() }}"
    no_proxy: "{{ no_proxy | default() }}"
  pre_tasks:
    - debug: var=hostvars[inventory_hostname]
  roles:
    - role: trombik.hosts
    - role: trombik.hostname
    - role: trombik.sudo
    - role: trombik.pf
    - role: trombik.zsh
    - role: trombik.vim
    - role: trombik.git
    - role: create_users
    - role: trombik.nsd
    - role: create_extra_groups
    - role: trombik.opensmtpd
    - role: trombik.dovecot
