---
- hosts:
  - virtualbox-mx
  - staging-mx
  - prod-mx
  become: yes
  become_method: "{% if 'virtualbox' in group_names %}sudo{% else %}doas{% endif %}"
  remote_user: ec2-user
  environment:
    http_proxy: "{{ http_proxy | default() }}"
    https_proxy: "{{ https_proxy | default() }}"
    no_proxy: "{{ no_proxy | default() }}"
  pre_tasks:
    - debug: var=hostvars[inventory_hostname]
  roles:
    - trombik.hostname
    - trombik.pf
    - trombik.zsh
    - trombik.vim
    - trombik.git
    - create_users
    - create_extra_groups
    - trombik.opensmtpd
    - trombik.dovecot
