---

name: Lint
on:
  pull_request: null
  push: null

jobs:
  markdownlint-cli:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    name: Lint markdown files
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install and use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm packages
        run: npm install

      - name: Run markdownlint-cli
        run: node node_modules/markdownlint-cli/markdownlint.js .
  rubocop:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.6
    name: Lint ruby files with rubocop
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install ruby version ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install bundler and gems
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Run rubocop
        run: |
          bundle exec rake test:ci:rubocop
  aspell:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.6
    name: Check spellings in markdown files
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install ruby version ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install bundler and gems
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Install aspell
        run: |
          sudo apt-get install aspell aspell-en
          aspell --version

      - name: Run aspel
        run: |
          bundle exec rake test:ci:aspell
  yamllint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.6
        python-version:
          - 3.x
    name: Lint YAML files with yamllint
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install ruby version ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install bundler and gems
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Install python version ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install yamllint
        run: |
          pip3 install yamllint

      - name: Run yamllint
        run: |
          bundle exec rake test:ci:yamllint
